name: Sync Tailscale ACLs
on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main
    
jobs:
  acls:
    runs-on: self-hosted
    environment: witch-hut
    steps:
      - uses: actions/checkout@v3

      - name: Test ACL 
        if: github.event_name == 'pull_request'
        id: test-acl
        uses: tailscale/gitops-acl-action@v1
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          action: test
          policy-file: ./network/policy.hujson


      - name: Deploy ACL
        if: github.event_name == 'push'
        id: deploy-acl
        uses: tailscale/gitops-acl-action@v1
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tailnet: ${{ secrets.TS_TAILNET }}
          action: apply
          policy-file: ./network/policy.hujson
